### ISSUE TITLE
could Cardinal fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [himanshugoel2797/Cardinal-semicolon#1]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by himanshugoel2797** [comment]
Sorry for getting back to you so late. Cardinal; certainly is flexible enough to be made to potentially boot on a floppy, but the minimum target hardware is well beyond that point, being a 64-bit OS, that expects an extremely recent processor. 

Thanks for the interest though!

**Comment by informer2016** [comment]
@himanshugoel2797 sorry for my late reply as well :smile: As you could see, most of the hardware from https://www.coreboot.org/Supported_Motherboards list is still quite modern and powerful, ranging from the quad core laptops to the 16-core servers. These computers don't have a physical floppy drive at all, but if your OS would have had a floppy version - it would have been possible to include it directly to a coreboot BIOS image so that Cardinal could be ran directly from a BIOS chip! :smiley: Maybe even from your own computer - if you have a real chance to get a motherboard or laptop that is coreboot-supported
